### ISSUE TITLE
Single node networks break opt_einsum contractions.

### ISSUE THREAD

**Issue by Thenerdstation** [google/TensorNetwork#177]
```python
import numpy as np 
import tensornetwork

net = tensornetwork.TensorNetwork("numpy")
a = net.add_node(np.ones((2, 2, 2)))
# pylint: disable=pointless-statement
a[0] ^ a[1]
node = tensornetwork.contractors.optimal(net).get_final_node()
```

Causes

```
Traceback (most recent call last):
  File "check.py", line 8, in <module>
    node = tensornetwork.contractors.optimal(net).get_final_node()
  File "/usr/local/google/home/chaseriley/TensorNetwork/tensornetwork/contractors/opt_einsum_paths/path_contractors.py", line 59, in optimal
    return base(net, alg)
  File "/usr/local/google/home/chaseriley/TensorNetwork/tensornetwork/contractors/opt_einsum_paths/path_contractors.py", line 34, in base
    path = algorithm(input_sets, output_set, size_dict)
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/opt_einsum/paths.py", line 196, in optimal
    return ssa_to_linear(best['path'])
  File "/usr/local/google/home/chaseriley/.local/lib/python3.6/site-packages/opt_einsum/paths.py", line 28, in ssa_to_linear
    ids = np.arange(1 + max(map(max, ssa_path)), dtype=np.int32)
ValueError: max() arg is an empty sequence

```

**Comment by Thenerdstation** [comment]
This happens for all algorithms expect `auto`.
