### ISSUE TITLE
ncon_interface tests fail 

### ISSUE THREAD

**Issue by mganahl** [google/TensorNetwork#262]

**Comment by Thenerdstation** [comment]
You'll need to provide more context, as the tests pass on our Travis build.

**Comment by mganahl** [comment]
the test pass if pytest is run from the parent folder, but fail if ncon_interface_test.py is tested directly.

**Comment by Thenerdstation** [comment]
Please print the errors that it raises.

**Comment by MichaelMarien** [comment]
Hi,

I notice the following behaviour
* `pytest` runs without errors
* `pytest tensornetwork` fails

Reason: pytest does not "clean up" in between tests, which is also the reason it is so hard to mock the import fails on different backends.

Some of the tests in the experiments explicitly set the default backend back to tensorflow. This masks the problem that some test (the ones in `ncon_interface` are still assuming tensorflow is default although we switched to Numpy.

@mganahl if you can confirm this behaviour I can write a PR for it (fixing tests to make sure they work with Numpy as default backend)

@Thenerdstation perhaps we might want to have `pytest tensornetwork` explicitly in travis, as this is the one we are most interested in - for sure we can keep both?

**Comment by mganahl** [comment]
@MichaelMarien I can confirm this. I even get a more obscure problem on my `remove_tn` branch
which is that running pytest from the root dir causes two tests tensornetwork_tests.py fail, but
running the tensornetwork folder directly  produces no error.

**Comment by mganahl** [comment]
here is the error

```
_________________________________________________________________________________ test_add_copy_node_from_node_object[jax] _________________________________________________________________________________

backend = 'jax'

    def test_add_copy_node_from_node_object(backend):
      net = tensornetwork.TensorNetwork(backend=backend)
      a = net.add_node(
          tensornetwork.CopyNode(3, 3, name="TestName", axis_names=['a', 'b', 'c']))
      assert a in net
      assert a.shape == (3, 3, 3)
      assert isinstance(a, tensornetwork.CopyNode)
      assert a.name == "TestName"
      assert a.axis_names == ['a', 'b', 'c']
      b = net.add_node(np.eye(3))
      e = a[0] ^ b[0]
>     c = net.contract(e)

tensornetwork/tests/tensornetwork_test.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tensornetwork/network.py:1758: in contract
    new_node = self.add_node(contract(edge, name, axis_names=None))
tensornetwork/network.py:435: in contract
    [[edge.axis1], [edge.axis2]])
tensornetwork/backends/tensorflow/tensorflow_backend.py:44: in tensordot
    return tensordot2.tensordot(self.tf, a, b, axes)
tensornetwork/backends/tensorflow/tensordot2.py:234: in tensordot
    b = tf.convert_to_tensor(b, name="b")
../../../PY3_TF_1.14/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1087: in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
../../../PY3_TF_1.14/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1145: in convert_to_tensor_v2
    as_ref=False)
../../../PY3_TF_1.14/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1224: in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
../../../PY3_TF_1.14/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:305: in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
../../../PY3_TF_1.14/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:246: in constant
    allow_broadcast=True)
../../../PY3_TF_1.14/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:254: in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = DeviceArray([[1., 0., 0.],
             [0., 1., 0.],
             [0., 0., 1.]]), ctx = <tensorflow.python.eager.context.Context object at 0x1064362e8>, dtype = None

    def convert_to_eager_tensor(value, ctx, dtype=None):
      """Converts the given `value` to an `EagerTensor`.
    
      Note that this function could return cached copies of created constants for
      performance reasons.
    
      Args:
        value: value to convert to EagerTensor.
        ctx: value of context.context().
        dtype: optional desired dtype of the converted EagerTensor.
    
      Returns:
        EagerTensor created from value.
    
      Raises:
        TypeError: if `dtype` is not compatible with the type of t.
      """
      if isinstance(value, ops.EagerTensor):
        if dtype is not None and value.dtype != dtype:
          raise TypeError("Expected tensor with type %r not %r" % (
              dtype, value.dtype))
        return value
      if dtype is not None:
        try:
          dtype = dtype.as_datatype_enum
        except AttributeError:
          dtype = dtypes.as_dtype(dtype).as_datatype_enum
      ctx.ensure_initialized()
      device = ctx.device_name
      handle = ctx._handle  # pylint: disable=protected-access
      if isinstance(value, (float,) + six.integer_types):
        # Use a scalar cache. This will put each scalar of each type only once on
        # each device. Scalars don't use much device memory but copying scalars can
        # trigger memcpys which are slow.
        cache_key = device, value, dtype, type(value)
        scalar_cache = ctx.scalar_cache()
        tensor = scalar_cache.get(cache_key, None)
        if tensor is not None:
          return ops.EagerTensor(
              value, handle, device, dtype, tensor)
        t = ops.EagerTensor(value, handle, device, dtype)
        scalar_cache[cache_key] = t
        return t
      else:
>       return ops.EagerTensor(value, handle, device, dtype)
E       ValueError: TypeError: len() of unsized object
E       Traceback (most recent call last):
E       
E         File "/Users/martin/PY3_TF_1.14/lib/python3.7/site-packages/jax/interpreters/xla.py", line 601, in __len__
E           return self.shape[0]
E       
E       IndexError: tuple index out of range
E       
E       
E       During handling of the above exception, another exception occurred:
E       
E       
E       Traceback (most recent call last):
E       
E         File "/Users/martin/PY3_TF_1.14/lib/python3.7/site-packages/jax/interpreters/xla.py", line 603, in __len__
E           raise TypeError("len() of unsized object")  # same as numpy error
E       
E       TypeError: len() of unsized object

../../../PY3_TF_1.14/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:115: ValueError
------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------
[[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 1.]]]
<tensornetwork.backends.tensorflow.tensorflow_backend.TensorFlowBackend object at 0x17d0d8c50>
```

**Comment by Thenerdstation** [comment]
Ok, so in this case it seems like the tensorflow backend was being used during a JAX test, we should look into this some more.
